-When changing Leader names, don't forget to put a | between every name, and make sure you write each word with a starting capital.
-Delete ';' for Leaderchoice in order to use this preset
[Leaders]
;LeaderChoice=Leader Name 1|Leader Name 2|Leader Name 3|Et Ce Te Ra
[NicksItem]
NicksModel=1617
[ResignItem]
ResignModel=31155
[PickupLoot]
Pickup=True
nopickup=False
green=True
gold=True
purple=True
blue=True
white=False
allmats=True
raremats=True
pcons=True
tomes=False
Openchests=True
[FightOptions]
FightYes=True
FightNO=False
Radio_Placement=2
[Skills]
Skill1=True
Skill2=True
Skill3=True
Skill4=True
Skill5=True
Skill6=True
Skill7=False
Skill8=False
[WindowSettings]
OnTop=False
